from django.contrib import admin
from django.urls import path

from oppurtune import views

urlpatterns = [
    path('',views.login,name='login'),
    path('login_post',views.login_post,name='login_post'),
    path('admin_home',views.admin_home,name='admin_home'),
    path('view_feedback',views.view_feedback,name='view_feedback'),
    path('view_jobprovider',views.view_jobprovider,name='view_jobprovider'),
    path('accept_jobprovider/<id>',views.accept_jobprovider,name='accept_jobprovider'),
    path('reject_jobprovider/<id>',views.reject_jobprovider,name='reject_jobprovider'),
    path('view_verifiedjobprovider',views.view_verifiedjobprovider,name='view_verifiedjobprovider'),
    path('send_reply/<id>',views.send_reply,name='send_reply'),
    path('veiw_complaint',views.veiw_complaint,name='veiw_complaint'),
    path('editProfilePost',views.editProfilePost,name='editProfilePost'),

    path('send_reply_post',views.send_reply_post,name='send_reply_post'),
    path('view_users_table',views.view_users_table,name='view_users_table'),
    path('worker_registration',views.worker_registration,name='worker_registration'),
    path('worker_register_post',views.worker_register_post,name='worker_register_post'),
    path('worker_home_page', views.worker_home_page, name='worker_home_page'),
    path('view_work_request', views.view_work_request, name='view_work_request'),
    path('work_status', views.work_status, name='work_status'),
    path('work_status_update', views.work_status_update, name='work_status_update'),
    path('accept_work/<id>', views.accept_work, name='accept_work'),
    path('reject_work/<id>', views.reject_work, name='reject_work'),
    path('manage_rate', views.manage_rate, name='manage rate'),
    path('new_rate', views.new_rate, name='new_rate'),
    path('new_rate_post', views.new_rate_post, name='new_rate_post'),
    path('edit_rate/<id>', views.edit_rate, name='edit_rate'),
    path('edit_rate_post', views.edit_rate_post, name='edit_rate_post'),
    path('delete_rate/<id>', views.delete_rate, name='delete_rate'),
    path('view_profile',views.view_profile, name='view_profile'),
    path('veiw_complaint_jp',views.veiw_complaint_jp, name='veiw_complaint_jp'),
    path('edit_profile',views.edit_profile, name='edit_profile'),
    path('job_provider_registration', views.worker_registration, name='job_provider_registration'),
    path('add_job_opening', views.add_job_opening, name='add_job_opening'),
    path('job_provider_feedback', views.job_provider_feedback, name='job_provider_feedback'),
    path('job_provider_register_post', views.job_provider_register_post, name='job_provider_register_post'),
    path('Jobopening', views.Jobopening, name='Jobopening'),
    path('view_rating', views.view_rating, name='view_rating'),
    path('veiw_user', views.veiw_user, name='veiw_user'),
    path('verifyjobprovider', views.verifyjobprovider, name='verifyjobprovider'),
    path('job_provider_register', views.job_provider_register, name='job_provider_register'),
    path('job_provider_home_page', views.job_provider_home_page, name='job_provider_home_page'),
    path('add_job_opening', views.add_job_opening, name='add_job_opening'),
    path('add_job_opening_post', views.add_job_opening_post, name='add_job_opening_post'),
    path('Delete_jobopenings/<id>', views.Delete_jobopenings, name='Delete_jobopenings'),
    path('edit_job_openings/<id>', views.edit_job_openings, name='edit_job_openings'),
    path('accept_jobrequest/<id>', views.accept_jobrequest, name='accept_jobrequest'),
    path('reject_jobrequest/<id>', views.reject_jobrequest, name='reject_jobrequest'),
    path('edit_job_opening_post', views.edit_job_opening_post, name='edit_job_opening_post'),
    path('chatwithuser', views.chatwithuser, name='chatwithuser'),
    path('chatview', views.chatview, name='chatview'),
    path('user_register', views.user_register, name='user_register'),
    path('view_job', views.view_job, name='view_job'),
    path('Viewrating', views.Viewrating, name='Viewrating'),
    path('veiw_reply', views.veiw_reply, name='veiw_reply'),
    path('view_worker', views.view_worker, name='view_worker'),
    path('veiw_request_status', views.veiw_request_status, name='veiw_request_status'),
    path('view_application_status', views.view_application_status, name='view_application_status'),
    path('coun_msg/<int:id>', views.coun_msg, name='coun_msg'),
    path('coun_insert_chat/<str:msg>/<int:id>', views.coun_insert_chat, name='coun_insert_chat'),
    path('and_login_post', views.and_login_post, name='and_login_post'),
    path('user_register', views.user_register, name='user_register'),
    path('Sendrequest', views.Sendrequest, name='Sendrequest'),
    path('Viewrequest_status', views.Viewrequest_status, name='Viewrequest_status'),
    path('view_profile_user', views.view_profile_user, name='view_profile_user'),

    path('ViewMyComplaints', views.ViewMyComplaints, name='ViewMyComplaints'),
    path('SendAppComplaint', views.SendAppComplaint, name='SendAppComplaint'),
    path('DeleteMyComplaint', views.DeleteMyComplaint, name='DeleteMyComplaint'),
    path('addrating', views.addrating, name='addrating'),
    path('apply_for_job', views.apply_for_job, name='apply_for_job'),
    path('forgot_password', views.forgot_password, name='forgot_password'),
    path('view_worker_det', views.view_worker_det, name='view_worker_det'),
    path('User_sendchat', views.User_sendchat, name='User_sendchat'),
    path('User_viewchat', views.User_viewchat, name='User_viewchat'),
    path('web_forgot_password', views.web_forgot_password, name='web_forgot_password'),

]
