# Generated by Django 5.1.2 on 2024-12-09 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='job_provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('email', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('pin', models.BigIntegerField()),
                ('photo', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='login_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='job_opening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(max_length=100)),
                ('no_of_vaccancy', models.IntegerField()),
                ('qualification', models.CharField(max_length=100)),
                ('experience', models.IntegerField()),
                ('salary', models.BigIntegerField()),
                ('due_date', models.DateField()),
                ('JOB_PROVIDER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oppurtune.job_provider')),
            ],
        ),
        migrations.AddField(
            model_name='job_provider',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oppurtune.login_table'),
        ),
        migrations.CreateModel(
            name='job_application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('JOB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oppurtune.job_opening')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oppurtune.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('fromid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_id', to='oppurtune.login_table')),
                ('toid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_id', to='oppurtune.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='users_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='')),
                ('phone', models.BigIntegerField()),
                ('place', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('pin', models.BigIntegerField()),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oppurtune.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('replay', models.CharField(max_length=100)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oppurtune.users_table')),
            ],
        ),
        migrations.CreateModel(
            name='workers_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='')),
                ('phone', models.BigIntegerField()),
                ('place', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('pin', models.IntegerField()),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oppurtune.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='work_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oppurtune.users_table')),
                ('WORKER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oppurtune.workers_table')),
            ],
        ),
        migrations.CreateModel(
            name='rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oppurtune.users_table')),
                ('WORKER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oppurtune.workers_table')),
            ],
        ),
        migrations.CreateModel(
            name='rate_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worktype', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=100)),
                ('rate', models.CharField(max_length=100)),
                ('WORKER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oppurtune.workers_table')),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('rating', models.CharField(max_length=100)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oppurtune.users_table')),
                ('WORKER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oppurtune.workers_table')),
            ],
        ),
    ]
